--- 
repo: openworm/owmeta-core
shortDescription: "Unified, simple data access python library for data & facts about C. elegans anatomy"
coordinator: Mark Watts (@mwatts15)
outputs: 
  - openworm/c302
  - openworm/ChannelWorm
  - openworm/owmeta
parent:
  - openworm/OpenWorm
children:
  - openworm/ChannelWorm
