language: python

python:
- 3.9
- 3.8
- 3.7
- 3.6

matrix:
  include:
  - python: '3.8'
    env:
    - DEPLOY=1

services:
- postgresql
- mysql

before_install:
- pip install --upgrade pip
- pip install coveralls
- if [ "$DEPLOY" ] ; then pip install twine ; fi
- pip uninstall pytest --yes
- pip install pytest>=3.4.0

install:
- "./ci-install.sh"

script:
- if [ ! "$DEPLOY" ] ; then ./ci-test.sh ; fi

after_script:
- coveralls

after_success:
- "./.travis.success.sh"

env:
  global:
  - SQLITE_TEST=1 POSTGRES_TEST=1 MYSQL_TEST=1
  - TWINE_USERNAME=__token__
  - COVERALLS_PARALLEL=true
  - secure: RhcUYxzwQckmv98xT0XxS1V8Y/uKXe2uu61Bau93JbeQ18wVq/Ya6xtyYt2TUyiJ1j/6mRvqakh4MqEyqy3Mz6iRsLXfv21Ql7Bf21EpRhLVIjaQlipcCoLWVOwOYiSnNa/K7yezHpwmH5aqBeY45XwTvytUsaLW5oiSQhMD7e5ymRg8WfFeuxWutpViHP7/30U0DaiiyPa0BXM2D3Osi2WjQLvBIjb5W5162m4GM/ul93kFyssjn+rolAQsoFCNzbfSskDuudZtO6mHKgxtiTQZYUagHZqf1b0zU03nCgQOBg2wfrRaTB/Lr/VDGuNfJgimjEshUvjaqH6zz8jz/UEWTHyDqmwMJTziK9TBS32IP0X0BtPbCqqQiQZDJWi3yMn4sIg9lWTIOAl6c+Tz3wHKNb0PRN6YxGG9j3V/7mK1ciAiftaGUFB71TGc5i9dOFhaNUXSVGr+yk39vbVCHsqbV9vZUerQedZ1yp5TnGnAhFbdb2sCIfcf8WXmqXxtBbemDAsrRuc26DJxUchZ1GY2DweWi68CdQdL/CvVHYn/v7YAXPNcuViCs3ftPTIUGXYz0psA9n0N+OYLERsaIefiP23Wy0tFcXwiJc2gDF2R8mPBOffom2y1Fu7vYhM1X7UuYfZgmxrX4rQqJX6+39Ge6nHVGGAZTaz73mIUnLk=
  - secure: sonU6hCrXcfojz7QlPlHENNO9ZeFB66/+plG8m1R8fPj/iXKJG+CGeq/rpJCVH/aiseV/lZkdf6sTowlhFaJXU+nMXmKcM39FJXRhpUWwqIc4wfeujGqzJGdexVhekIaNL8IiEspmgBG0QgUQzZ+Td6Mi4srI0lFHEs2E16IoCcNv/N9gA53bTz0IZ2EEAV6LhpHiFMgOj5mG51v0SsB3KkayQimEh03OBzvHjhxVw3MomAWcL6vU05rWhf+D5q59YIyNLRwHAsVRyGm5DJLWUhSepD9JelYbgNfRILV0PbaZXhDkr2rwGXbDCLLgU9hGj7Wll6ZhZJjiqh0IGTTcFW5QRT5NeEQPd6o+NUA/7D0hSQsG+XZJFy/eR7eI39unwe+ZrIuXgNrzQZk8w8newjYyUnolKKWw/XAB5QbTpiLH8FJMe9jp4aJ9jxKrRJltV/Bw10LiTOCNOLTCsahhpgpsi7BCe7/njQpSgAZ0f8oc20FMPalaNPsIZWqn+y09R3mwoKYa4klUP1sHCCSi0IViMrIPZRfSjeVm1EHU26HPUDINasdyiRjl/MAzZnXI/mGfm4iOLUTFeFD47LI6aoSeiV6rTbKU3vuHc4pfXQ9ywhbwbF1NkAgiNYoY/JV3FBstGu82OgTIKWRoxMPjSdhCIQxSCm315EUNCzR404=
notifications:
  webhooks: https://coveralls.io/webhook
