language: python

python:
- 3.8
- 3.7
- 3.6

services:
- postgresql
- mysql

before_install:
- pip install --upgrade pip
- pip install coveralls
- pip uninstall pytest --yes
- pip install pytest>=3.4.0

install:
- ./ci-install.sh

script:
- ./ci-test.sh

after_script:
- coveralls

after_success:
- ./codespeed-submit.sh

env:
  global:
  - SQLITE_TEST=1 POSTGRES_TEST=1 MYSQL_TEST=1
  - COVERALLS_PARALLEL=true
notifications:
  webhooks: https://coveralls.io/webhook
