name: Build master

on:
  schedule:
    # minute 39 of every hour
    - cron:  '39 * * * *'

jobs:
  test:
    uses: openworm/owmeta-core/test.yml@github-workflows
    with:
      ref: refs/heads/develop
