name: Build develop

on:
  schedule:
    - cron:  '27 8,14,20,2 * * *'

jobs:
  test:
    uses: openworm/owmeta-core/.github/workflows/test.yml@github-workflows
    with:
      ref: refs/heads/develop
